apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: aks-nvme-ssd-provisioner
  labels:
    app: aks-nvme-ssd-provisioner
spec:
  selector:
    matchLabels:
      name: aks-nvme-ssd-provisioner
  template:
    metadata:
      labels:
        name: aks-nvme-ssd-provisioner
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        agentpool: infras
      priorityClassName: system-node-critical
      containers:
        - name: aks-nvme-ssd-provisioner
          image: registry.sandbox.beehexa.com/hexasync/aks-nvme-ssd-provisioner:202207100848
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /hx-disks
              name: hx-disks
              mountPropagation: "Bidirectional"
      volumes:
        - name: hx-disks
          hostPath:
            path: /hx-disks
